version: "3.8"
services:
  issai_qazllm:
    build:
      context: .
      dockerfile: Dockerfile
    image: issai_qazllm:latest
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=0,1
      - DIR=${DIR}  # Pass the COMMAND as an environment variable
      - HF_ALLOW_CODE_EVAL=1
      - TOKENIZERS_PARALLELISM=false
    volumes:
      - ${PWD}:/issai_qazllm
      # - /data/nvme3n1p1/adal_workspace/models/issai_llama_8b:/issai_qazllm/models/issai_llama_8b
    ports:
      - "3434:3434"
    # devices:
    #   - "/dev/nvidia0:/dev/nvidia0"
    #   - "/dev/nvidia1:/dev/nvidia1"
    command: /bin/sh -c 'python3 $DIR'
