version: "3.8"
services:
  issai_qazllm:
    build:
      context: .
      dockerfile: Dockerfile
    image: issai_qazllm:latest
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - COMMAND=${COMMAND}  # Pass the COMMAND as an environment variable
    volumes:
      - ${PWD}:/issai_qazllm
    ports:
      - "3434:3434"
    devices:
      - "/dev/nvidia0:/dev/nvidia0"
      - "/dev/nvidia1:/dev/nvidia1"
    # entrypoint: ["bash", "-c", "source /opt/venv/bin/activate && exec \"$COMMAND\""]  # Ensure virtualenv is activated
    command: /bin/sh -c 'python3 $DIR'
