
model_path: "meta-llama/Llama-3.2-1B-Instruct"
model_name: "Llama-3.2-1B-Instruct"
benchmarks:
  - "gsm8k"
  - "arc"
  - "mmlu"
  - "drop"
  - "hellaswag"
  - "humaneval"
  - "winogrande"
languages:
  - "kk"
  - "ru"
  - "en"
batch_size: 64
tensor_parallel_size: 8
data_portion: 100
max_tokens:
  mmlu: 15
  arc: 30
  drop: 40
  gsm8k: 512
  humaneval: 512
  hellaswag: 15
  winogrande: 15
is_local_model: False
