# Tokenizer
tokenizer:
  _component_: torchtune.models.llama3.llama3_tokenizer
  path: tokenizer_path

# Dataset
dataset:
  _component_: torchtune.datasets.text_completion_dataset
  split: train
  column: text
  source: json
  data_files: dataset_path/*.json
  val_data_files_kk: val_dataset_path/val_kk_1000.json
  val_data_files_ru: val_dataset_path/val_ru_1000.json
  val_data_files_en: val_dataset_path/val_en_1000.json
  val_data_files_tr: val_dataset_path/val_tr_1000.json
  max_seq_len: 8192
  packed: True
seed: null
shuffle: False


# Model Arguments
model:
  _component_: torchtune.models.llama3_1.llama3_1_8b

checkpointer:
  _component_: torchtune.utils.FullModelHFCheckpointer
  checkpoint_dir: model_8B
  checkpoint_files: [
    hf_model_0001_14000.pt,
    hf_model_0002_14000.pt,
    hf_model_0003_14000.pt,
    hf_model_0004_14000.pt   
  ]
  recipe_checkpoint: null
  output_dir: checkpoints
  model_type: LLAMA3
resume_from_checkpoint: False

# Fine-tuning arguments
batch_size: 3
batch_size_val: 1
epochs: 2
save_per_step: 1000

optimizer:
  _component_: torch.optim.AdamW
  lr: 2e-5
  foreach: False

loss:
  _component_: torch.nn.CrossEntropyLoss
max_steps_per_epoch: null
gradient_accumulation_steps: 1


# Training env
device: cuda

# Memory management
enable_activation_checkpointing: True
memory_efficient_fsdp_wrap: True

# Reduced precision
dtype: bf16

# Logging

# metric_logger:
#   _component_: torchtune.utils.metric_logging.DiskLogger
#   log_dir: ${output_dir}
# output_dir: logs
# log_every_n_steps: 1
# log_peak_memory_stats: False

# enable logging to the built-in WandBLogger
metric_logger:
  _component_: torchtune.utils.metric_logging.WandBLogger
  # the W&B project to log to
  project: _
  name: _
output_dir: logs
log_every_n_steps: 1
log_peak_memory_stats: False

sub_length: 100000
train_type: base