version: "3.10"
services:
  
  vllm:
    build:
      context: .
      dockerfile: Dockerfile
    image: vllm_image:latest
    runtime: nvidia
    ports:
      - "8003:8003"
    # network_mode: "host"  
    networks:
      app_network:
        ipv4_address: 172.28.0.2  # Static IP for vllm container
    command: "python3 src/scripts/run_vllm.py"
    volumes:
      - ${PWD}:/ui_qazllm
      - ../models:/ui_qazllm/models
      - ../conf:/ui_qazllm/conf

  ui:
    container_name: issai_qazllm_ui
    build:
      context: .
      dockerfile: Dockerfile_fastapi
    ports:
      - "8035:8035"
    working_dir: "/ui_qazllm"
    # network_mode: "host"
    networks:
      app_network:
        ipv4_address: 172.28.0.3  # Static IP for ui container
    depends_on:
      - vllm
    environment:
      - MODEL_SERVER_URL=http://172.28.0.2:8003  # Static IP of vllm container
    command: >
      bash -c "ls models && ls conf && python3 src/main.py"
    volumes:
      - ${PWD}:/ui_qazllm
      - ../models:/ui_qazllm/models
      - ../conf:/ui_qazllm/conf

networks:
  app_network:
    driver: bridge
    ipam:
      config:
        - subnet: "172.28.0.0/16"  # Define subnet for static IPs
